name: youngcleopatra
favicon: null
layout_spectrum: 0.35291
typography_spectrum: 0.77463
title: THE LAST PHARAOH
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#998678'
    - '#bea68c'
    - '#434432'
    - '#f9d587'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.2866335690487176
  rhythmicContrast: 0.75
purpose: []
