name: youngcleopatra
favicon: null
layout_spectrum: 0.03710991772823036
typography_spectrum: 0.11868662852793932
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.7022734561469406
  lightness: 0.6220758832059801
  saturation: 0.2866335690487176
  rhythmicContrast: 0.6006983101833612
purpose: []
