title: THE LAST PHARAOH
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.2866335690487176
  brandStrength: 1
  lightness: 0.5
  brandColors:
    - '#FFFFFF'
    - '#9A8779'
    - '#424230'
    - '#F2C688'
    - '#9498BC'
  rhythmicContrast: 0.75
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: youngcleopatra
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.77463
layout_spectrum: 0.6765957
