title: THE LAST PHARAOH
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.2866335690487176
  brandStrength: 1
  rhythmicContrast: 0.75
  brandColors:
    - '#ffffff'
    - '#998678'
    - '#bea68c'
    - '#434432'
    - '#f9d587'
  lightness: 0.5
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: youngcleopatra
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.77463
layout_spectrum: 0.4914894
