name: youngcleopatra
favicon: null
layout_spectrum: 0
typography_spectrum: 0.07161
title: THE LAST PHARAOH
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FFFFFF'
    - '#9A8779'
    - '#424230'
    - '#F2C688'
    - '#9498BC'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.2866335690487176
  rhythmicContrast: 0.75
purpose: []
